// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/text.proto

package toolkits

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Keyword
type KeywordRequest struct {
	Text                 string   `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeywordRequest) Reset()         { *m = KeywordRequest{} }
func (m *KeywordRequest) String() string { return proto.CompactTextString(m) }
func (*KeywordRequest) ProtoMessage()    {}
func (*KeywordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7867fa29f069f605, []int{0}
}

func (m *KeywordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeywordRequest.Unmarshal(m, b)
}
func (m *KeywordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeywordRequest.Marshal(b, m, deterministic)
}
func (m *KeywordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeywordRequest.Merge(m, src)
}
func (m *KeywordRequest) XXX_Size() int {
	return xxx_messageInfo_KeywordRequest.Size(m)
}
func (m *KeywordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_KeywordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_KeywordRequest proto.InternalMessageInfo

func (m *KeywordRequest) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

type KeywordResponse struct {
	Text                 []string `protobuf:"bytes,1,rep,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeywordResponse) Reset()         { *m = KeywordResponse{} }
func (m *KeywordResponse) String() string { return proto.CompactTextString(m) }
func (*KeywordResponse) ProtoMessage()    {}
func (*KeywordResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7867fa29f069f605, []int{1}
}

func (m *KeywordResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeywordResponse.Unmarshal(m, b)
}
func (m *KeywordResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeywordResponse.Marshal(b, m, deterministic)
}
func (m *KeywordResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeywordResponse.Merge(m, src)
}
func (m *KeywordResponse) XXX_Size() int {
	return xxx_messageInfo_KeywordResponse.Size(m)
}
func (m *KeywordResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_KeywordResponse.DiscardUnknown(m)
}

var xxx_messageInfo_KeywordResponse proto.InternalMessageInfo

func (m *KeywordResponse) GetText() []string {
	if m != nil {
		return m.Text
	}
	return nil
}

// Summary
type SummaryRequest struct {
	Text                 string   `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Count                int64    `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SummaryRequest) Reset()         { *m = SummaryRequest{} }
func (m *SummaryRequest) String() string { return proto.CompactTextString(m) }
func (*SummaryRequest) ProtoMessage()    {}
func (*SummaryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7867fa29f069f605, []int{2}
}

func (m *SummaryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SummaryRequest.Unmarshal(m, b)
}
func (m *SummaryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SummaryRequest.Marshal(b, m, deterministic)
}
func (m *SummaryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SummaryRequest.Merge(m, src)
}
func (m *SummaryRequest) XXX_Size() int {
	return xxx_messageInfo_SummaryRequest.Size(m)
}
func (m *SummaryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SummaryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SummaryRequest proto.InternalMessageInfo

func (m *SummaryRequest) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *SummaryRequest) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type SummaryResponse struct {
	Text                 string   `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SummaryResponse) Reset()         { *m = SummaryResponse{} }
func (m *SummaryResponse) String() string { return proto.CompactTextString(m) }
func (*SummaryResponse) ProtoMessage()    {}
func (*SummaryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7867fa29f069f605, []int{3}
}

func (m *SummaryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SummaryResponse.Unmarshal(m, b)
}
func (m *SummaryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SummaryResponse.Marshal(b, m, deterministic)
}
func (m *SummaryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SummaryResponse.Merge(m, src)
}
func (m *SummaryResponse) XXX_Size() int {
	return xxx_messageInfo_SummaryResponse.Size(m)
}
func (m *SummaryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SummaryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SummaryResponse proto.InternalMessageInfo

func (m *SummaryResponse) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

// Tf-idf
type TFRequest struct {
	Text                 []string `protobuf:"bytes,1,rep,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TFRequest) Reset()         { *m = TFRequest{} }
func (m *TFRequest) String() string { return proto.CompactTextString(m) }
func (*TFRequest) ProtoMessage()    {}
func (*TFRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7867fa29f069f605, []int{4}
}

func (m *TFRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TFRequest.Unmarshal(m, b)
}
func (m *TFRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TFRequest.Marshal(b, m, deterministic)
}
func (m *TFRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TFRequest.Merge(m, src)
}
func (m *TFRequest) XXX_Size() int {
	return xxx_messageInfo_TFRequest.Size(m)
}
func (m *TFRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TFRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TFRequest proto.InternalMessageInfo

func (m *TFRequest) GetText() []string {
	if m != nil {
		return m.Text
	}
	return nil
}

type TFResponse struct {
	Records              []*TFRecord `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *TFResponse) Reset()         { *m = TFResponse{} }
func (m *TFResponse) String() string { return proto.CompactTextString(m) }
func (*TFResponse) ProtoMessage()    {}
func (*TFResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7867fa29f069f605, []int{5}
}

func (m *TFResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TFResponse.Unmarshal(m, b)
}
func (m *TFResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TFResponse.Marshal(b, m, deterministic)
}
func (m *TFResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TFResponse.Merge(m, src)
}
func (m *TFResponse) XXX_Size() int {
	return xxx_messageInfo_TFResponse.Size(m)
}
func (m *TFResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TFResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TFResponse proto.InternalMessageInfo

func (m *TFResponse) GetRecords() []*TFRecord {
	if m != nil {
		return m.Records
	}
	return nil
}

type TFRecord struct {
	Text                 string   `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Score                float32  `protobuf:"fixed32,2,opt,name=score,proto3" json:"score,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TFRecord) Reset()         { *m = TFRecord{} }
func (m *TFRecord) String() string { return proto.CompactTextString(m) }
func (*TFRecord) ProtoMessage()    {}
func (*TFRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_7867fa29f069f605, []int{6}
}

func (m *TFRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TFRecord.Unmarshal(m, b)
}
func (m *TFRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TFRecord.Marshal(b, m, deterministic)
}
func (m *TFRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TFRecord.Merge(m, src)
}
func (m *TFRecord) XXX_Size() int {
	return xxx_messageInfo_TFRecord.Size(m)
}
func (m *TFRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_TFRecord.DiscardUnknown(m)
}

var xxx_messageInfo_TFRecord proto.InternalMessageInfo

func (m *TFRecord) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *TFRecord) GetScore() float32 {
	if m != nil {
		return m.Score
	}
	return 0
}

func init() {
	proto.RegisterType((*KeywordRequest)(nil), "pbuf.KeywordRequest")
	proto.RegisterType((*KeywordResponse)(nil), "pbuf.KeywordResponse")
	proto.RegisterType((*SummaryRequest)(nil), "pbuf.SummaryRequest")
	proto.RegisterType((*SummaryResponse)(nil), "pbuf.SummaryResponse")
	proto.RegisterType((*TFRequest)(nil), "pbuf.TFRequest")
	proto.RegisterType((*TFResponse)(nil), "pbuf.TFResponse")
	proto.RegisterType((*TFRecord)(nil), "pbuf.TFRecord")
}

func init() { proto.RegisterFile("protos/text.proto", fileDescriptor_7867fa29f069f605) }

var fileDescriptor_7867fa29f069f605 = []byte{
	// 291 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x52, 0x4f, 0x4b, 0xfb, 0x40,
	0x10, 0x6d, 0xda, 0xfc, 0x7e, 0xda, 0x51, 0x12, 0xbb, 0x54, 0x28, 0x5e, 0x2c, 0x8b, 0x42, 0x4e,
	0x11, 0x5a, 0xf1, 0xe0, 0x45, 0x11, 0x14, 0xc4, 0xdb, 0x9a, 0x93, 0xb7, 0x36, 0xd9, 0x80, 0x68,
	0x3b, 0x71, 0x77, 0x83, 0xed, 0x97, 0xf3, 0xb3, 0xc9, 0xfe, 0x4b, 0x6c, 0x8b, 0xde, 0x76, 0xde,
	0xbc, 0x79, 0xf3, 0xe6, 0xb1, 0x30, 0xa8, 0x04, 0x2a, 0x94, 0x17, 0x8a, 0xaf, 0x54, 0x6a, 0xde,
	0x24, 0xac, 0xe6, 0x75, 0x49, 0xcf, 0x20, 0x7a, 0xe2, 0xeb, 0x4f, 0x14, 0x05, 0xe3, 0x1f, 0x35,
	0x97, 0x8a, 0x10, 0x08, 0x35, 0x6b, 0x14, 0x8c, 0x83, 0xa4, 0xcf, 0xcc, 0x9b, 0x9e, 0x43, 0xdc,
	0xb0, 0x64, 0x85, 0x4b, 0xc9, 0x7f, 0xd0, 0x7a, 0x0d, 0xed, 0x1a, 0xa2, 0xe7, 0x7a, 0xb1, 0x98,
	0x89, 0xf5, 0x1f, 0x62, 0x64, 0x08, 0xff, 0x72, 0xac, 0x97, 0x6a, 0xd4, 0x1d, 0x07, 0x49, 0x8f,
	0xd9, 0x42, 0xaf, 0x68, 0x66, 0x77, 0x56, 0xb4, 0x4e, 0x4e, 0xa1, 0x9f, 0x3d, 0xec, 0xaa, 0xb7,
	0x1e, 0xae, 0x00, 0x34, 0xc1, 0x49, 0x24, 0xb0, 0x27, 0x78, 0x8e, 0xa2, 0x90, 0x86, 0x74, 0x30,
	0x89, 0x52, 0x7d, 0x76, 0xaa, 0x29, 0x1a, 0x66, 0xbe, 0x4d, 0x2f, 0x61, 0xdf, 0x83, 0xbf, 0xb9,
	0x96, 0x39, 0x0a, 0x6e, 0x5c, 0x77, 0x99, 0x2d, 0x26, 0x5f, 0x01, 0x84, 0x99, 0x6e, 0xdf, 0x42,
	0x7c, 0xbf, 0x52, 0x62, 0x96, 0x2b, 0x17, 0x94, 0x24, 0x43, 0xbb, 0x6a, 0x33, 0xde, 0x93, 0xe3,
	0x2d, 0xd4, 0x1a, 0xa5, 0x1d, 0x72, 0x03, 0x91, 0x53, 0x70, 0x39, 0x78, 0x81, 0xcd, 0x48, 0xbd,
	0xc0, 0x56, 0x58, 0xb4, 0x43, 0xa6, 0x70, 0xe8, 0x04, 0xb2, 0xf2, 0xb1, 0x28, 0x49, 0xdc, 0x9e,
	0x6a, 0x27, 0x8f, 0x5a, 0xc0, 0x0f, 0xdd, 0x0d, 0x5e, 0x62, 0xff, 0x35, 0x10, 0xdf, 0xdf, 0x5e,
	0x95, 0x9c, 0xff, 0x37, 0xc0, 0xf4, 0x3b, 0x00, 0x00, 0xff, 0xff, 0x6d, 0xe3, 0x07, 0x79, 0x34,
	0x02, 0x00, 0x00,
}
